"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { loadAccessContext } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function value(form:FormData,key:string,min=1,max=500){const v=String(form.get(key)??"").trim();return v.length>=min&&v.length<=max?v:null;}
async function admit(dealId:string){const c=await loadAccessContext();if(c.kind==="unauthenticated")redirect("/login");if(c.kind!=="ready")redirect(`/app/deals/${dealId}?error=not-authorized`);const cohort=(process.env.BUDDY_GOLDEN_LOAN_FACTORY_ORGANIZATION_IDS??"").split(",").map(x=>x.trim());if(process.env.BUDDY_GOLDEN_LOAN_FACTORY_ENABLED!=="true"||!cohort.includes(c.activeOrganization.organizationId))redirect(`/app/deals/${dealId}?error=not-enabled`);return c;}
async function command(form:FormData,name:string,args:Record<string,unknown>,saved:string){const dealId=value(form,"dealId",36,36);if(!dealId||!UUID.test(dealId))redirect("/app/deals");const c=await admit(dealId),s=await createClient();const{error}=await s.rpc(name,{p_organization_id:c.activeOrganization.organizationId,p_deal_id:dealId,...args});if(error)redirect(`/app/deals/${dealId}?error=command-failed`);revalidatePath(`/app/deals/${dealId}`);redirect(`/app/deals/${dealId}?saved=${saved}`);}
export async function certifyMemo(form:FormData){const memo=value(form,"memoId",36,36),statement=value(form,"statement",8,500),key=value(form,"key",8,160);if(!memo||!statement||!key)return;return command(form,"certify_credit_memo",{p_memo_id:memo,p_statement:statement,p_idempotency_key:key},"memo-certified");}
export async function voteCredit(form:FormData){const memo=value(form,"memoId",36,36),vote=value(form,"vote",3,20),rationale=value(form,"rationale",3,1000);if(!memo||!vote||!rationale)return;return command(form,"record_credit_committee_vote",{p_memo_id:memo,p_vote:vote,p_rationale:rationale},"vote-recorded");}
export async function decideCredit(form:FormData){const memo=value(form,"memoId",36,36),decision=value(form,"decision",3,40),rationale=value(form,"rationale",3,1000),key=value(form,"key",8,160);if(!memo||!decision||!rationale||!key)return;return command(form,"record_human_credit_decision",{p_memo_id:memo,p_decision:decision,p_rationale:rationale,p_idempotency_key:key},"credit-decided");}
export async function addCreditCondition(form:FormData){const memo=value(form,"memoId",36,36),description=value(form,"description",3,1000),key=value(form,"key",8,160);if(!memo||!description||!key)return;return command(form,"create_credit_condition",{p_memo_id:memo,p_description:description,p_due_at:value(form,"dueAt",10,40),p_idempotency_key:key},"condition-added");}
export async function addClosingRequirement(form:FormData){const title=value(form,"title",2,200),key=value(form,"key",8,160);if(!title||!key)return;return command(form,"create_closing_requirement",{p_title:title,p_due_at:value(form,"dueAt",10,40),p_required:true,p_idempotency_key:key},"closing-added");}
export async function authorizeFunding(form:FormData){const decision=value(form,"decisionId",36,36),amount=Number(form.get("amount")),evidence=value(form,"evidence",3,500),key=value(form,"key",8,160);if(!decision||!Number.isFinite(amount)||amount<=0||!evidence||!key)return;return command(form,"golden_authorize_deal_funding",{p_decision_id:decision,p_amount:amount,p_evidence_reference:evidence,p_idempotency_key:key},"funding-authorized");}
export async function boardDeal(form:FormData){const account=value(form,"accountNumber",2,100),key=value(form,"key",8,160);if(!account||!key)return;return command(form,"golden_board_funded_deal",{p_account_number:account,p_next_review_date:value(form,"nextReviewDate",10,10),p_idempotency_key:key},"deal-boarded");}
