import {createHash} from "node:crypto";
import type {CreditAssessment} from "./credit-engine";
export const CREDIT_MEMO_VERSION="buddy-credit-memo.v1" as const;
export type MemoInput={dealId:string;assessmentId:string;assessment:CreditAssessment;borrower:string;request:{amount:number;purpose:string;termMonths:number};sources:string[];analystNarrative?:string};
export type CreditMemo={version:typeof CREDIT_MEMO_VERSION;dealId:string;assessmentId:string;borrower:string;request:MemoInput["request"];repayment:{globalDscr:number|null;proposedLoanCoverage:number|null;stressC:number|null};collateral:CreditAssessment["collateral"];guarantor:CreditAssessment["guarantor"];risk:CreditAssessment["risk"];exceptions:CreditAssessment["exceptions"];sources:string[];analystNarrative:string|null;requiresHumanCertification:true;contentHash:string};
export function buildCreditMemo(input:MemoInput):CreditMemo{const body={version:CREDIT_MEMO_VERSION,dealId:input.dealId,assessmentId:input.assessmentId,borrower:input.borrower.trim(),request:input.request,repayment:{globalDscr:input.assessment.cashFlow.globalDscr,proposedLoanCoverage:input.assessment.cashFlow.proposedLoanCoverage,stressC:input.assessment.stress.find(s=>s.scenario==="stress_c_binding")?.dscr??null},collateral:input.assessment.collateral,guarantor:input.assessment.guarantor,risk:input.assessment.risk,exceptions:input.assessment.exceptions,sources:[...new Set(input.sources)].sort(),analystNarrative:input.analystNarrative?.trim()||null,requiresHumanCertification:true as const};return{...body,contentHash:createHash("sha256").update(stable(body)).digest("hex")};}
const stable=(value:unknown):string=>value===null||typeof value!=="object"?JSON.stringify(value):Array.isArray(value)?`[${value.map(stable).join(",")}]`:`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(",")}}`;
export type CommitteePolicy={version:string;loanAmountThreshold:number;dscrFloor:number;ltvLimit:number;committeeOnExceptions:boolean;requiredVotes:number;requiredApproverRoles:Array<"owner"|"administrator"|"underwriter">};
export function evaluateCommitteeRequirement(memo:CreditMemo,policy:CommitteePolicy){const reasons:string[]=[];if(memo.request.amount>policy.loanAmountThreshold)reasons.push("LOAN_AMOUNT_THRESHOLD");if(memo.repayment.globalDscr!=null&&memo.repayment.globalDscr<policy.dscrFloor)reasons.push("DSCR_BELOW_COMMITTEE_FLOOR");if(memo.collateral.ltv!=null&&memo.collateral.ltv>policy.ltvLimit)reasons.push("LTV_ABOVE_COMMITTEE_LIMIT");if(policy.committeeOnExceptions&&memo.exceptions.length)reasons.push("POLICY_EXCEPTIONS_PRESENT");return{policyVersion:policy.version,required:reasons.length>0,reasons,requiredVotes:reasons.length?policy.requiredVotes:1,requiredApproverRoles:policy.requiredApproverRoles};}
export type DecisionReadinessInput={memoCertified:boolean;memoHashMatches:boolean;assessmentReviewed:boolean;openMaterialExceptions:number;conditionsHaveOwners:boolean;committeeRequired:boolean;committeeVotes:number;requiredVotes:number;approverRole:string;requiredApproverRoles:string[];decision:"approved"|"approved_with_conditions"|"declined"|"returned";rationale:string;conditions:number};
export function validateCreditDecision(input:DecisionReadinessInput){const blockers:string[]=[];if(!input.memoCertified)blockers.push("MEMO_NOT_CERTIFIED");if(!input.memoHashMatches)blockers.push("MEMO_HASH_MISMATCH");if(!input.assessmentReviewed)blockers.push("ASSESSMENT_NOT_REVIEWED");if(input.openMaterialExceptions>0)blockers.push("MATERIAL_EXCEPTIONS_UNRESOLVED");if(!input.conditionsHaveOwners)blockers.push("CONDITIONS_MISSING_OWNER");if(input.committeeRequired&&input.committeeVotes<input.requiredVotes)blockers.push("COMMITTEE_QUORUM_NOT_MET");if(!input.requiredApproverRoles.includes(input.approverRole))blockers.push("APPROVAL_AUTHORITY_REQUIRED");if(!input.rationale.trim())blockers.push("RATIONALE_REQUIRED");if(input.decision==="approved_with_conditions"&&input.conditions===0)blockers.push("CONDITIONS_REQUIRED");return{ready:blockers.length===0,blockers,requiresHumanAction:true as const};}
