export const CREDIT_ENGINE_VERSION="buddy-credit-engine.v1" as const;
export type CreditPolicy={version:string;dscrFloor:number;stressDscrFloor:number;stressRevenueCompression:number;stressRateBps:number;leverageMax:number;currentRatioMin:number;ltvLimit:number;pdGrade2Factor:number;pdGrade3Factor:number;pdSpecialMentionMin:number;pdSubstandardMin:number;lgdStrong:number;lgdAdequate:number;lgdWeak:number};
export const DEFAULT_CREDIT_POLICY:CreditPolicy={version:"buddy-policy-default.v1",dscrFloor:1.15,stressDscrFloor:1,stressRevenueCompression:.15,stressRateBps:300,leverageMax:4.5,currentRatioMin:1,ltvLimit:.8,pdGrade2Factor:1.5,pdGrade3Factor:1.2,pdSpecialMentionMin:1,pdSubstandardMin:.9,lgdStrong:1.25,lgdAdequate:1,lgdWeak:.75};
export type PolicyException={code:string;actual:number|null;limit:number;severity:"warning"|"material";message:string};
export type CollateralItem={type:"real_estate"|"equipment"|"accounts_receivable"|"inventory"|"blanket_lien"|"vehicle"|"other";value:number;advanceRate?:number;lienPosition?:number};
export type CreditInputs={ncads:number|null;businessCashFlows:number[];personalIncome:number;personalLivingExpenses:number;businessDebtService:number;personalDebtService:number;proposedDebtService:number;stressedDebtService300?:number;revenue:number;grossMarginPct:number;leverage:number|null;currentRatio:number|null;collateral:CollateralItem[];loanExposure:number;guarantorLiquidity:number;guarantorContingentLiabilities:number;projectedDscr?:number|null;deterioratingTrend?:boolean;characterConcern?:boolean};
export type CreditAssessment={engineVersion:typeof CREDIT_ENGINE_VERSION;policyVersion:string;cashFlow:{globalCashFlow:number;annualDebtService:number;dscr:number|null;globalDscr:number|null;proposedLoanCoverage:number|null};collateral:{grossValue:number;lendableValue:number;ltv:number|null;coverage:number|null;juniorLien:boolean};guarantor:{netLiquidity:number;supportStrength:number};stress:Array<{scenario:string;cashFlow:number;debtService:number;dscr:number|null;passes:boolean|null}>;risk:{pdGrade:number;pd:number;lgd:number;classification:"PASS"|"SPECIAL_MENTION"|"SUBSTANDARD"|"DOUBTFUL"|"LOSS";drivers:string[]};exceptions:PolicyException[];requiresHumanReview:true};
const ADVANCE:Record<CollateralItem["type"],number>={real_estate:.8,equipment:.75,accounts_receivable:.8,inventory:.5,blanket_lien:.7,vehicle:.75,other:.5};
const ratio=(n:number|null,d:number|null)=>n==null||d==null||!Number.isFinite(n)||!Number.isFinite(d)||d<=0?null:n/d;
export function computeCreditAssessment(input:CreditInputs,policy:CreditPolicy=DEFAULT_CREDIT_POLICY):CreditAssessment{
 const annualDebtService=input.businessDebtService+input.personalDebtService+input.proposedDebtService;
 const globalCashFlow=input.businessCashFlows.reduce((a,b)=>a+b,0)+input.personalIncome-input.personalLivingExpenses;
 const dscr=ratio(input.ncads,annualDebtService),globalDscr=ratio(globalCashFlow,annualDebtService),proposedLoanCoverage=ratio(input.ncads,input.proposedDebtService);
 const grossValue=input.collateral.reduce((a,c)=>a+c.value,0),lendableValue=input.collateral.reduce((a,c)=>a+c.value*(c.advanceRate??ADVANCE[c.type]),0),ltv=ratio(input.loanExposure,lendableValue),coverage=ratio(lendableValue,input.loanExposure),juniorLien=input.collateral.some(c=>(c.lienPosition??1)>1);
 const netLiquidity=Math.max(0,input.guarantorLiquidity-input.guarantorContingentLiabilities),supportStrength=input.loanExposure>0?Math.min(1,netLiquidity/input.loanExposure):0;
 const stressedDs=input.stressedDebtService300??annualDebtService*1.12,impact=input.revenue*policy.stressRevenueCompression*input.grossMarginPct,stress=[scenario("rate_up_300bps",globalCashFlow,stressedDs,policy.stressDscrFloor),scenario("revenue_down_15pct",globalCashFlow-impact,annualDebtService,policy.stressDscrFloor),scenario("stress_c_binding",globalCashFlow-impact,stressedDs,policy.stressDscrFloor)];
 const drivers:string[]=[];const gradeDscr=[globalDscr,input.projectedDscr].filter((v):v is number=>v!=null);const basis=gradeDscr.length?Math.min(...gradeDscr):null;let grade=basis==null?6:basis>=policy.dscrFloor*policy.pdGrade2Factor?2:basis>=policy.dscrFloor*policy.pdGrade3Factor?3:basis>=policy.dscrFloor?4:basis>=policy.pdSpecialMentionMin?6:basis>=policy.pdSubstandardMin?7:8;
 if(input.projectedDscr!=null&&globalDscr!=null&&input.projectedDscr<globalDscr)drivers.push("Forward-looking projected DSCR is lower than current global DSCR.");if(input.leverage!=null&&(input.leverage<0||input.leverage>policy.leverageMax)){grade++;drivers.push("Leverage exceeds policy or reflects negative EBITDA.");}if(input.currentRatio!=null&&input.currentRatio<policy.currentRatioMin){grade++;drivers.push("Current ratio is below policy.");}if(input.deterioratingTrend){grade++;drivers.push("Deteriorating performance trend.");}if(input.characterConcern){grade++;drivers.push("Material character or management concern.");}grade=Math.max(1,Math.min(9,grade));
 const pd=[.001,.0025,.005,.01,.025,.06,.15,.4,1][grade-1];let lgd=coverage==null?.75:coverage>=policy.lgdStrong?.2:coverage>=policy.lgdAdequate?.4:coverage>=policy.lgdWeak?.6:.85;if(juniorLien)lgd=Math.min(1,lgd+.1);lgd=Math.max(0,lgd-.1*supportStrength);lgd=Math.round(lgd*100)/100;const classification=grade<=5?"PASS":grade===6?"SPECIAL_MENTION":grade===7?"SUBSTANDARD":grade===8?(lgd>=.6?"DOUBTFUL":"SUBSTANDARD"):"LOSS";
 const exceptions:PolicyException[]=[];if(dscr!=null&&dscr<policy.dscrFloor)exceptions.push(exception("DSCR_BELOW_FLOOR",dscr,policy.dscrFloor));if(ltv!=null&&ltv>policy.ltvLimit)exceptions.push(exception("LTV_ABOVE_LIMIT",ltv,policy.ltvLimit));if(input.leverage!=null&&(input.leverage<0||input.leverage>policy.leverageMax))exceptions.push(exception("LEVERAGE_OUTSIDE_POLICY",input.leverage,policy.leverageMax));if(stress[2].passes===false)exceptions.push(exception("STRESS_C_FAILED",stress[2].dscr,policy.stressDscrFloor));
 return{engineVersion:CREDIT_ENGINE_VERSION,policyVersion:policy.version,cashFlow:{globalCashFlow,annualDebtService,dscr,globalDscr,proposedLoanCoverage},collateral:{grossValue,lendableValue,ltv,coverage,juniorLien},guarantor:{netLiquidity,supportStrength},stress,risk:{pdGrade:grade,pd,lgd,classification,drivers:[...drivers,"Recommended grade is deterministic; human approval and overrides are separate governed actions."]},exceptions,requiresHumanReview:true};
}
const scenario=(name:string,cashFlow:number,debtService:number,floor:number)=>{const dscr=ratio(cashFlow,debtService);return{scenario:name,cashFlow,debtService,dscr,passes:dscr==null?null:dscr>=floor};};
const exception=(code:string,actual:number|null,limit:number):PolicyException=>({code,actual,limit,severity:actual!=null&&actual<1?"material":"warning",message:`${code}: actual ${actual??"unknown"}; policy ${limit}.`});
