import{describe,expect,it}from"vitest";import{computeCreditAssessment,DEFAULT_CREDIT_POLICY,type CreditInputs}from"./credit-engine";
const base:CreditInputs={ncads:300000,businessCashFlows:[300000],personalIncome:0,personalLivingExpenses:0,businessDebtService:100000,personalDebtService:0,proposedDebtService:100000,stressedDebtService300:230000,revenue:2000000,grossMarginPct:.5,leverage:2,currentRatio:1.5,collateral:[{type:"real_estate",value:350000,lienPosition:1}],loanExposure:200000,guarantorLiquidity:100000,guarantorContingentLiabilities:0};
describe("Buddy credit engine source parity",()=>{
 it("uses canonical headline DSCR NCADS divided by all annual debt service",()=>{const r=computeCreditAssessment(base);expect(r.cashFlow.dscr).toBe(1.5);expect(r.cashFlow.proposedLoanCoverage).toBe(3);});
 it("reproduces Stress C simultaneous 15 percent revenue compression and stressed debt service",()=>{const r=computeCreditAssessment(base);expect(r.stress[2]).toMatchObject({scenario:"stress_c_binding",cashFlow:150000,debtService:230000,passes:false});expect(r.stress[2].dscr).toBeCloseTo(.65217);});
 it("uses lendable collateral rather than gross collateral for LTV",()=>{const r=computeCreditAssessment(base);expect(r.collateral.lendableValue).toBe(280000);expect(r.collateral.ltv).toBeCloseTo(.714286);});
 it("grades on the lower forward-looking DSCR and raises LGD for junior thin collateral",()=>{const weak={...base,projectedDscr:.95,leverage:3,collateral:[{type:"other" as const,value:280000,lienPosition:2}],guarantorLiquidity:0};const r=computeCreditAssessment(weak);expect(r.risk.pdGrade).toBeGreaterThanOrEqual(7);expect(["SUBSTANDARD","DOUBTFUL"]).toContain(r.risk.classification);expect(r.risk.lgd).toBeGreaterThan(.4);});
 it("allows versioned tenant policy without changing formulas",()=>{const r=computeCreditAssessment(base,{...DEFAULT_CREDIT_POLICY,version:"bank-tight-v1",dscrFloor:1.6});expect(r.policyVersion).toBe("bank-tight-v1");expect(r.exceptions.map(x=>x.code)).toContain("DSCR_BELOW_FLOOR");});
 it("never turns deterministic risk into an approval",()=>{expect(computeCreditAssessment(base).requiresHumanReview).toBe(true);expect(computeCreditAssessment(base).risk.drivers.join(" ")).toMatch(/human approval/);});
});
