import {describe,expect,it,vi} from "vitest"; import {parseDocumentIntelligenceProviderConfig,submitDocumentIntelligence,DocumentIntelligenceProviderError} from "./document-intelligence-provider"; import {DOCUMENT_INTELLIGENCE_CONTRACT_VERSION,type DocumentIntelligenceRequest} from "./document-intelligence";
const config={endpoint:"https://intelligence.example/analyze",apiKey:"provider-secret-long-enough",provider:"buddy-adapter"};
const request:DocumentIntelligenceRequest={contractVersion:DOCUMENT_INTELLIGENCE_CONTRACT_VERSION,jobId:"job-1",organizationId:"org-1",dealId:"deal-1",documentId:"doc-1",documentVersionId:"version-1",sha256:"a".repeat(64),mediaType:"application/pdf"};
const result={...request,provider:config.provider,model:null,engineVersion:"engine-1",classification:{canonicalType:"bank_statement",confidence:.9,tier:"deterministic_anchor" as const,classifierVersion:"classifier-1",reason:"anchor",requiresHumanReview:false,evidence:[]},fields:[],tables:[],completedAt:"2026-08-12T12:00:00.000Z"};
describe("document intelligence provider",()=>{
 it("requires complete HTTPS server configuration",()=>{expect(parseDocumentIntelligenceProviderConfig({BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_ENDPOINT:config.endpoint,BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_API_KEY:config.apiKey,BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_PROVIDER:config.provider})).toEqual(config);expect(parseDocumentIntelligenceProviderConfig({BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_ENDPOINT:"http://unsafe"})).toBeNull();});
 it("sends authenticated versioned multipart without redirects",async()=>{const fetchImpl=vi.fn(async(_u:string|URL|Request,init?:RequestInit)=>{expect(init?.redirect).toBe("error");expect(new Headers(init?.headers).get("idempotency-key")).toBe("job-1:version-1");const body=init?.body as FormData;expect(JSON.parse(String(body.get("request"))).sha256).toBe(request.sha256);return Response.json(result);});await expect(submitDocumentIntelligence(config,request,new Blob(["doc"]),fetchImpl as typeof fetch)).resolves.toEqual(result);});
 it.each([[429,true],[503,true],[400,false]])("classifies HTTP %i retryability",async(status,retryable)=>{const failure=await submitDocumentIntelligence(config,request,new Blob(),vi.fn(async()=>new Response("secret",{status})) as typeof fetch).catch(x=>x);expect(failure).toBeInstanceOf(DocumentIntelligenceProviderError);expect(failure).toMatchObject({retryable});expect((failure as Error).message).not.toContain("secret");});
});
