import {describe,expect,it,vi} from "vitest"; import {parseDocumentIntelligenceProviderConfig,submitDocumentIntelligence,DocumentIntelligenceProviderError} from "./document-intelligence-provider"; import {DOCUMENT_INTELLIGENCE_CONTRACT_VERSION,type DocumentIntelligenceRequest} from "./document-intelligence";
const config={endpoint:"https://intelligence.example/analyze",apiKey:"provider-secret-long-enough",provider:"buddy-adapter",googleServiceAccount:null};
const request:DocumentIntelligenceRequest={contractVersion:DOCUMENT_INTELLIGENCE_CONTRACT_VERSION,jobId:"job-1",organizationId:"org-1",dealId:"deal-1",documentId:"doc-1",documentVersionId:"version-1",sha256:"a".repeat(64),mediaType:"application/pdf"};
const result={...request,provider:config.provider,model:null,engineVersion:"engine-1",classification:{canonicalType:"bank_statement",confidence:.9,tier:"deterministic_anchor" as const,classifierVersion:"classifier-1",reason:"anchor",requiresHumanReview:false,evidence:[]},fields:[],tables:[],completedAt:"2026-08-12T12:00:00.000Z"};
describe("document intelligence provider",()=>{
 it("requires complete HTTPS server configuration",()=>{expect(parseDocumentIntelligenceProviderConfig({BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_ENDPOINT:config.endpoint,BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_API_KEY:config.apiKey,BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_PROVIDER:config.provider})).toEqual(config);expect(parseDocumentIntelligenceProviderConfig({BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_ENDPOINT:"http://unsafe"})).toBeNull();});
 it("fails closed for private Cloud Run without valid Google credentials",()=>{const env={BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_ENDPOINT:"https://buddy-private.us-west1.run.app/api/providers/buddy-los/document-intelligence",BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_API_KEY:config.apiKey,BUDDY_UNDERWRITER_DOCUMENT_INTELLIGENCE_PROVIDER:config.provider};expect(parseDocumentIntelligenceProviderConfig(env)).toBeNull();expect(parseDocumentIntelligenceProviderConfig({...env,BUDDY_UNDERWRITER_GOOGLE_SERVICE_ACCOUNT_JSON:"not-json"})).toBeNull();});
 it("sends private Cloud Run identity separately from the provider key",async()=>{const privateConfig={...config,endpoint:"https://buddy-private.us-west1.run.app/api/providers/buddy-los/document-intelligence",googleServiceAccount:{client_email:"los-invoker@example.iam.gserviceaccount.com",private_key:"-----BEGIN PRIVATE KEY-----\\ntest\\n-----END PRIVATE KEY-----"}};const identity=vi.fn(async(_credentials:unknown,audience:string)=>{expect(audience).toBe("https://buddy-private.us-west1.run.app");return "google-identity-token";});const fetchImpl=vi.fn(async(_u:string|URL|Request,init?:RequestInit)=>{const headers=new Headers(init?.headers);expect(headers.get("authorization")).toBe(`Bearer ${config.apiKey}`);expect(headers.get("x-serverless-authorization")).toBe("Bearer google-identity-token");return Response.json(result);});await submitDocumentIntelligence(privateConfig,request,new Blob(["doc"]),fetchImpl as typeof fetch,identity);expect(identity).toHaveBeenCalledOnce();});
 it("sends authenticated versioned multipart without redirects",async()=>{const fetchImpl=vi.fn(async(_u:string|URL|Request,init?:RequestInit)=>{expect(init?.redirect).toBe("error");expect(new Headers(init?.headers).get("idempotency-key")).toBe("job-1:version-1");const body=init?.body as FormData;expect(JSON.parse(String(body.get("request"))).sha256).toBe(request.sha256);return Response.json(result);});await expect(submitDocumentIntelligence(config,request,new Blob(["doc"]),fetchImpl as typeof fetch)).resolves.toEqual(result);});
 it.each([[429,true],[503,true],[400,false]])("classifies HTTP %i retryability",async(status,retryable)=>{const failure=await submitDocumentIntelligence(config,request,new Blob(),vi.fn(async()=>new Response("secret",{status})) as typeof fetch).catch(x=>x);expect(failure).toBeInstanceOf(DocumentIntelligenceProviderError);expect(failure).toMatchObject({retryable});expect((failure as Error).message).not.toContain("secret");});
});
