"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { loadAccessContext } from "@/lib/auth/session";
import { writesEnabledForOrganization } from "@/lib/config/foundation-status";
import { canOperateCore, dateTimeValue, optionalText, requiredText, uuidValue } from "@/lib/los/core-operations";
import { createClient } from "@/lib/supabase/server";

async function contextFor(dealId:string){const c=await loadAccessContext();if(c.kind==="unauthenticated")redirect("/login");if(c.kind!=="ready")redirect(`/app/deals/${dealId}?error=not-authorized`);if(!writesEnabledForOrganization(c.activeOrganization.organizationId))redirect(`/app/deals/${dealId}?error=not-enabled`);if(!canOperateCore(c.activeOrganization.role))redirect(`/app/deals/${dealId}?error=not-authorized`);return c;}
export async function createDealTask(form:FormData){const dealId=uuidValue(form,"dealId");if(!dealId)redirect("/app/deals");const c=await contextFor(dealId), key=requiredText(form,"idempotencyKey",8,160),title=requiredText(form,"title",2,200),description=optionalText(form,"description",4000),dueAt=dateTimeValue(form,"dueAt",true),assignedTo=uuidValue(form,"assignedTo",true);if(!key||!title||description===null||dueAt===undefined||assignedTo===undefined)redirect(`/app/deals/${dealId}?error=invalid-input`);const s=await createClient();const{error}=await s.rpc("create_deal_task",{p_organization_id:c.activeOrganization.organizationId,p_deal_id:dealId,p_idempotency_key:key,p_title:title,p_description:description,p_due_at:dueAt,p_assigned_to:assignedTo});if(error)redirect(`/app/deals/${dealId}?error=command-failed`);revalidatePath(`/app/deals/${dealId}`);redirect(`/app/deals/${dealId}?saved=task`);}
export async function transitionDealStage(form:FormData){const dealId=uuidValue(form,"dealId");if(!dealId)redirect("/app/deals");const c=await contextFor(dealId),key=requiredText(form,"idempotencyKey",8,160),version=Number(form.get("version")),target=String(form.get("targetStage")??"");if(!key||!Number.isInteger(version)||version<1||!["intake","application","underwriting","withdrawn","declined"].includes(target))redirect(`/app/deals/${dealId}?error=invalid-input`);const s=await createClient();const{error}=await s.rpc("transition_deal_stage",{p_organization_id:c.activeOrganization.organizationId,p_deal_id:dealId,p_idempotency_key:key,p_expected_version:version,p_target_stage:target});if(error)redirect(`/app/deals/${dealId}?error=${error.code==="40001"?"version-conflict":"command-failed"}`);revalidatePath(`/app/deals/${dealId}`);revalidatePath("/app/deals");redirect(`/app/deals/${dealId}?saved=stage`);}
