import {sha256Hex} from "@/lib/los/document-upload"; import {createAdminClient} from "@/lib/supabase/admin"; import {DOCUMENT_INTELLIGENCE_CONTRACT_VERSION,validateDocumentIntelligenceResult,type DocumentIntelligenceRequest} from "@/lib/underwriting/document-intelligence"; import {DocumentIntelligenceProviderError,parseDocumentIntelligenceProviderConfig,submitDocumentIntelligence} from "@/lib/underwriting/document-intelligence-provider";
const INIT={headers:{"Cache-Control":"no-store"}};
export async function GET(request:Request){
 if(process.env.BUDDY_UNDERWRITER_RUNTIME_ENABLED!=="true") return Response.json({processed:false,reason:"disabled"},INIT);
 const secret=process.env.CRON_SECRET??""; if(secret.length<16||request.headers.get("authorization")!==`Bearer ${secret}`) return Response.json({error:"Unauthorized."},{status:401,...INIT});
 const config=parseDocumentIntelligenceProviderConfig(process.env); if(!config)return Response.json({error:"Underwriting provider is not configured."},{status:503,...INIT});
 let admin;try{admin=createAdminClient();}catch{return Response.json({error:"Underwriting service is unavailable."},{status:503,...INIT});}
 const {data,error}=await admin.rpc("claim_underwriting_outbox_event");const claim=data as Record<string,unknown>|null;if(error)return Response.json({error:"Underwriting queue is unavailable."},{status:502,...INIT});if(!claim)return Response.json({processed:false,reason:"empty"},INIT);
 const eventId=String(claim.eventId),jobId=String(claim.jobId),organizationId=String(claim.organizationId),dealId=String(claim.dealId),documents=claim.documents as Array<Record<string,unknown>>;
 try{
  for(const document of documents){const path=String(document.path),bucket=String(document.bucket),sha256=String(document.sha256),mediaType=String(document.mediaType),documentId=String(document.documentId),documentVersionId=String(document.documentVersionId);const {data:blob,error:readError}=await admin.storage.from(bucket).download(path,{}, {cache:"no-store"});if(readError||!blob||blob.size!==Number(document.sizeBytes)||await sha256Hex(blob)!==sha256)throw new DocumentIntelligenceProviderError("Stored document failed underwriting verification.",false);
   const providerRequest:DocumentIntelligenceRequest={contractVersion:DOCUMENT_INTELLIGENCE_CONTRACT_VERSION,jobId,organizationId,dealId,documentId,documentVersionId,sha256,mediaType};const result=await submitDocumentIntelligence(config,providerRequest,blob);const errors=validateDocumentIntelligenceResult(providerRequest,result);if(errors.length)throw new DocumentIntelligenceProviderError(`Document intelligence validation failed: ${errors.join(",")}.`,false);const {error:recordError}=await admin.rpc("record_document_intelligence_artifact",{p_event_id:eventId,p_result:result});if(recordError)throw new DocumentIntelligenceProviderError("Document intelligence artifact could not be recorded.",true);
  }
  const {error:completeError}=await admin.rpc("complete_underwriting_document_intelligence",{p_event_id:eventId});if(completeError)throw new DocumentIntelligenceProviderError("Underwriting completion could not be recorded.",true);return Response.json({processed:true,jobId,status:"needs_review"},INIT);
 }catch(caught){const failure=caught instanceof DocumentIntelligenceProviderError?caught:new DocumentIntelligenceProviderError("Underwriting runtime failed.",true);await admin.rpc("fail_underwriting_runtime",{p_event_id:eventId,p_error:failure.message,p_retryable:failure.retryable});return Response.json({processed:true,jobId,status:failure.retryable?"queued":"failed"},INIT);}
}
