-- Canonical human-controlled closing, funding, boarding, and portfolio lifecycle.
create type public.lifecycle_item_status as enum ('open','satisfied','waived');
create type public.portfolio_risk_grade as enum ('pass','special_mention','substandard','doubtful','loss');
alter table public.credit_decisions add constraint credit_decisions_id_organization_unique unique(id,organization_id);

create table public.closing_requirements(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,deal_id uuid not null,title text not null check(length(trim(title)) between 2 and 200),status public.lifecycle_item_status not null default 'open',is_required boolean not null default true,due_at timestamptz,resolution_rationale text,resolved_by uuid references auth.users(id),resolved_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(id,organization_id),foreign key(deal_id,organization_id) references public.deals(id,organization_id),check((status='open' and resolved_at is null and resolved_by is null) or (status<>'open' and resolved_at is not null and resolved_by is not null and length(trim(resolution_rationale))>0))
);
create table public.funding_authorizations(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,deal_id uuid not null,decision_id uuid not null,amount numeric(18,2) not null check(amount>0),authorized_by uuid not null references auth.users(id),authorized_at timestamptz not null default now(),evidence_reference text not null check(length(trim(evidence_reference)) between 3 and 500),idempotency_key text not null,created_at timestamptz not null default now(),unique(id,organization_id),unique(organization_id,idempotency_key),unique(deal_id),foreign key(deal_id,organization_id) references public.deals(id,organization_id),foreign key(decision_id,organization_id) references public.credit_decisions(id,organization_id)
);
create table public.servicing_accounts(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,deal_id uuid not null,funding_authorization_id uuid not null,account_number text not null,boarded_by uuid not null references auth.users(id),boarded_at timestamptz not null default now(),principal_balance numeric(18,2) not null check(principal_balance>=0),next_review_date date,status text not null default 'active' check(status in('active','watch','paid_off','charged_off')),version integer not null default 1,unique(id,organization_id),unique(organization_id,account_number),unique(deal_id),foreign key(deal_id,organization_id) references public.deals(id,organization_id),foreign key(funding_authorization_id,organization_id) references public.funding_authorizations(id,organization_id)
);
create table public.portfolio_covenants(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,servicing_account_id uuid not null,title text not null check(length(trim(title)) between 2 and 200),due_date date not null,status public.lifecycle_item_status not null default 'open',owner_user_id uuid not null references auth.users(id),completed_at timestamptz,evidence_reference text,created_at timestamptz not null default now(),unique(id,organization_id),foreign key(servicing_account_id,organization_id) references public.servicing_accounts(id,organization_id),check((status='open' and completed_at is null) or (status<>'open' and completed_at is not null and length(trim(evidence_reference))>0))
);
create table public.portfolio_risk_history(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null,servicing_account_id uuid not null,risk_grade public.portfolio_risk_grade not null,rationale text not null check(length(trim(rationale)) between 3 and 4000),effective_at timestamptz not null default now(),recorded_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(id,organization_id),foreign key(servicing_account_id,organization_id) references public.servicing_accounts(id,organization_id)
);
create index closing_requirements_queue_idx on public.closing_requirements(organization_id,deal_id,status,due_at);
create index portfolio_covenants_queue_idx on public.portfolio_covenants(organization_id,status,due_date);
create index portfolio_risk_history_timeline_idx on public.portfolio_risk_history(organization_id,servicing_account_id,effective_at desc);

alter table public.closing_requirements enable row level security;alter table public.funding_authorizations enable row level security;alter table public.servicing_accounts enable row level security;alter table public.portfolio_covenants enable row level security;alter table public.portfolio_risk_history enable row level security;
revoke all on public.closing_requirements,public.funding_authorizations,public.servicing_accounts,public.portfolio_covenants,public.portfolio_risk_history from public,anon,authenticated;
grant select on public.closing_requirements,public.funding_authorizations,public.servicing_accounts,public.portfolio_covenants,public.portfolio_risk_history to authenticated;
create policy closing_read_member on public.closing_requirements for select to authenticated using(exists(select 1 from public.organization_memberships m where m.organization_id=closing_requirements.organization_id and m.user_id=(select auth.uid()) and m.is_active));
create policy funding_read_member on public.funding_authorizations for select to authenticated using(exists(select 1 from public.organization_memberships m where m.organization_id=funding_authorizations.organization_id and m.user_id=(select auth.uid()) and m.is_active));
create policy servicing_read_member on public.servicing_accounts for select to authenticated using(exists(select 1 from public.organization_memberships m where m.organization_id=servicing_accounts.organization_id and m.user_id=(select auth.uid()) and m.is_active));
create policy covenant_read_member on public.portfolio_covenants for select to authenticated using(exists(select 1 from public.organization_memberships m where m.organization_id=portfolio_covenants.organization_id and m.user_id=(select auth.uid()) and m.is_active));
create policy risk_read_member on public.portfolio_risk_history for select to authenticated using(exists(select 1 from public.organization_memberships m where m.organization_id=portfolio_risk_history.organization_id and m.user_id=(select auth.uid()) and m.is_active));

create function public.require_lifecycle_operator(p_organization_id uuid,p_roles public.organization_role[]) returns public.organization_role language plpgsql security definer set search_path='' as $$declare v_role public.organization_role;begin select m.role into v_role from public.organization_memberships m where m.organization_id=p_organization_id and m.user_id=(select auth.uid()) and m.is_active;if v_role is null or not(v_role=any(p_roles)) then raise exception using errcode='42501',message='Lifecycle operation permission denied.';end if;return v_role;end$$;
revoke all on function public.require_lifecycle_operator(uuid,public.organization_role[]) from public,anon,authenticated;

create function public.authorize_deal_funding(p_organization_id uuid,p_deal_id uuid,p_decision_id uuid,p_amount numeric,p_evidence_reference text,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_id uuid;v_result jsonb;begin perform public.require_lifecycle_operator(p_organization_id,array['owner','administrator','closer']::public.organization_role[]);if length(trim(coalesce(p_idempotency_key,''))) not between 8 and 160 then raise exception using errcode='22023',message='Invalid funding command.';end if;perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text||':'||trim(p_idempotency_key),0));select e.payload->'result' into v_result from public.audit_events e where e.organization_id=p_organization_id and e.idempotency_key='funding:'||trim(p_idempotency_key);if v_result is not null then return v_result||jsonb_build_object('replayed',true);end if;if not exists(select 1 from public.credit_decisions c where c.id=p_decision_id and c.organization_id=p_organization_id and c.deal_id=p_deal_id and c.decision in('approved','approved_with_conditions')) then raise exception using errcode='42501',message='Approved human credit decision required.';end if;if exists(select 1 from public.credit_conditions c where c.organization_id=p_organization_id and c.deal_id=p_deal_id and c.status='open') or exists(select 1 from public.closing_requirements r where r.organization_id=p_organization_id and r.deal_id=p_deal_id and r.is_required and r.status='open') then raise exception using errcode='23514',message='Open conditions prohibit funding.';end if;insert into public.funding_authorizations(organization_id,deal_id,decision_id,amount,authorized_by,evidence_reference,idempotency_key) values(p_organization_id,p_deal_id,p_decision_id,p_amount,v_actor,trim(p_evidence_reference),trim(p_idempotency_key)) returning id into v_id;update public.deals set stage='funding',approved_amount=p_amount,updated_at=now(),version=version+1 where id=p_deal_id and organization_id=p_organization_id;v_result:=jsonb_build_object('fundingAuthorizationId',v_id,'dealId',p_deal_id,'replayed',false);insert into public.audit_events(organization_id,actor_user_id,event_type,entity_type,entity_id,correlation_id,idempotency_key,payload)values(p_organization_id,v_actor,'funding.authorized','deal',p_deal_id,gen_random_uuid(),'funding:'||trim(p_idempotency_key),jsonb_build_object('result',v_result,'amount',p_amount));return v_result;end$$;

create function public.board_funded_deal(p_organization_id uuid,p_deal_id uuid,p_account_number text,p_next_review_date date,p_idempotency_key text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_actor uuid:=(select auth.uid());v_funding public.funding_authorizations;v_id uuid;v_result jsonb;begin perform public.require_lifecycle_operator(p_organization_id,array['owner','administrator','closer']::public.organization_role[]);perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_organization_id::text||':'||trim(coalesce(p_idempotency_key,'')),0));select e.payload->'result' into v_result from public.audit_events e where e.organization_id=p_organization_id and e.idempotency_key='boarding:'||trim(p_idempotency_key);if v_result is not null then return v_result||jsonb_build_object('replayed',true);end if;select * into v_funding from public.funding_authorizations f where f.organization_id=p_organization_id and f.deal_id=p_deal_id;if v_funding.id is null then raise exception using errcode='23514',message='Funding authorization required.';end if;insert into public.servicing_accounts(organization_id,deal_id,funding_authorization_id,account_number,boarded_by,principal_balance,next_review_date)values(p_organization_id,p_deal_id,v_funding.id,trim(p_account_number),v_actor,v_funding.amount,p_next_review_date)returning id into v_id;update public.deals set stage='servicing',updated_at=now(),version=version+1 where id=p_deal_id and organization_id=p_organization_id;v_result:=jsonb_build_object('servicingAccountId',v_id,'dealId',p_deal_id,'replayed',false);insert into public.audit_events(organization_id,actor_user_id,event_type,entity_type,entity_id,correlation_id,idempotency_key,payload)values(p_organization_id,v_actor,'boarding.completed','servicing_account',v_id,gen_random_uuid(),'boarding:'||trim(p_idempotency_key),jsonb_build_object('result',v_result));return v_result;end$$;

revoke all on function public.authorize_deal_funding(uuid,uuid,uuid,numeric,text,text),public.board_funded_deal(uuid,uuid,text,date,text) from public,anon;grant execute on function public.authorize_deal_funding(uuid,uuid,uuid,numeric,text,text),public.board_funded_deal(uuid,uuid,text,date,text) to authenticated;
comment on table public.funding_authorizations is 'Immutable human funding authority; requires an approved human credit decision and no open required conditions.';
comment on table public.servicing_accounts is 'Canonical boarded-loan record created only from a funding authorization.';
