import { randomUUID } from "node:crypto";
import Link from "next/link";
import { archiveCrmContact, closeCrmRelationship, completeCrmTask, reopenCrmRelationship, updateCrmAppointment, updateCrmPerson, updateCrmReferral, updateCrmTask } from "@/app/app/crm/actions";
import { formatMoney } from "@/components/banker/BankerCommandCenter";
import { formatDateTimeLocalInZone, formatInTimeZone } from "@/lib/los/core-operations";
import type { BorrowerDirectoryRow, DealSummary } from "@/lib/los/read-model";
import type { CrmActivityRecord, CrmAppointmentRecord, CrmContactRecord, CrmMetrics, CrmOperatorRecord, CrmPersonRecord, CrmReferralRecord, CrmRelationshipRecord, DealTaskRecord } from "@/lib/los/queries";

const tabs = ["home", "companies", "people", "relationships", "opportunities", "activities", "referrals", "calendar", "tasks", "insights", "reports"] as const;
type Props = { rows:BorrowerDirectoryRow[]; contacts:CrmContactRecord[]; relationships:CrmRelationshipRecord[]; deals:DealSummary[]; activities:CrmActivityRecord[]; tasks:DealTaskRecord[]; people:CrmPersonRecord[]; referrals:CrmReferralRecord[]; appointments:CrmAppointmentRecord[]; operators:CrmOperatorRecord[]; metrics:CrmMetrics; query:string; view:string; page:number; viewTotal:number; timezone:string; writesEnabled:boolean };

export function BorrowerDirectory(props:Props) {
  const activeView=tabs.includes(props.view as (typeof tabs)[number])?props.view:"home";
  const matches=(values:string[])=>!props.query||values.join(" ").toLocaleLowerCase().includes(props.query.trim().toLocaleLowerCase());
  const contacts=props.contacts.filter(x=>matches([x.borrowerName,x.kind,x.label??"",x.value]));
  const people=props.people.filter(x=>matches([x.firstName,x.lastName,x.preferredName??"",x.borrowerName,x.roleLabel,x.jobTitle??"",x.email??"",x.phone??""]));
  const relationships=props.relationships.filter(x=>matches([x.sourceName,x.targetName??"",x.dealName??"",x.kind,x.roleLabel??""]));
  const deals=props.deals.filter(x=>matches([x.borrowerName,x.name,x.dealNumber??"",x.stage]));
  const activities=props.activities.filter(x=>matches([x.borrowerName,x.kind,x.subject,x.notes??""]));
  const referrals=props.referrals.filter(x=>matches([x.borrowerName,x.sourceName,x.dealName??"",x.status,x.notes??""]));
  const appointments=props.appointments.filter(x=>matches([x.borrowerName,x.dealName??"",x.subject,x.location??"",x.status]));
  const tasks=props.tasks.filter(x=>matches([x.dealName,x.title,x.status,x.description??""]));
  return <section className="crm-command-center">
    <header className="crm-command-header"><div><p className="eyebrow">Relationship intelligence</p><h1>CRM Workspace</h1><p>Companies, people, referrals, appointments, opportunities, and work in one governed relationship system.</p></div><div className="header-actions"><Link className="secondary-button" href="/app/crm?view=activities#crm-operations">Log activity</Link><Link className="primary-button" href="/app/intake?surface=crm">Start governed loan deal</Link></div></header>
    <nav className="crm-tabs" aria-label="CRM sections">{tabs.map(tab=><Link key={tab} className={activeView===tab?"active":""} aria-current={activeView===tab?"page":undefined} href={`/app/crm?view=${tab}`}>{label(tab)}</Link>)}</nav>
    {activeView==="home"?<Home {...props}/>:<><Search view={activeView} query={props.query}/>
      {activeView==="companies"?<Companies rows={props.rows} total={props.viewTotal}/>:null}
      {activeView==="people"?<People people={people} contacts={contacts} total={props.viewTotal} writesEnabled={props.writesEnabled}/>:null}
      {activeView==="relationships"?<Relationships rows={relationships} total={props.viewTotal} writesEnabled={props.writesEnabled}/>:null}
      {activeView==="opportunities"?<Opportunities rows={deals} total={props.viewTotal}/>:null}
      {activeView==="activities"?<Activities rows={activities} total={props.viewTotal} timezone={props.timezone}/>:null}
      {activeView==="referrals"?<Referrals rows={referrals} total={props.viewTotal} timezone={props.timezone} writesEnabled={props.writesEnabled}/>:null}
      {activeView==="calendar"?<Appointments rows={appointments} operators={props.operators} total={props.viewTotal} timezone={props.timezone} writesEnabled={props.writesEnabled}/>:null}
      {activeView==="tasks"?<Tasks rows={tasks} operators={props.operators} total={props.viewTotal} timezone={props.timezone} writesEnabled={props.writesEnabled}/>:null}
      {activeView==="insights"||activeView==="reports"?<Insights metrics={props.metrics} report={activeView==="reports"}/>:null}
      <Pagination view={activeView} query={props.query} page={props.page} total={props.viewTotal}/>
    </>}
  </section>;
}

function Home({rows,activities,metrics,timezone}:Props){const missing=rows.filter(row=>!row.primaryContact).length;return <>
  <section className="crm-search-deck"><p>Search the relationship book</p><div className="crm-action-row"><form action="/app/crm"><input type="hidden" name="view" value="companies"/><input name="q" aria-label="Search the relationship book" placeholder="Company, person, relationship, activity..."/></form><Link href="/app/crm?view=companies#crm-operations">+ Add Company</Link><Link href="/app/crm?view=people#crm-operations">+ Add Contact</Link><Link href="/app/crm?view=relationships#crm-operations">+ Add Relationship</Link><Link href="/app/crm?view=calendar#crm-operations">+ Schedule</Link></div></section>
  <div className="crm-metric-grid"><Metric label="Assigned companies" value={String(metrics.companies)} detail="authorized companies"/><Metric label="People" value={String(metrics.people)} detail={`${metrics.contactPoints} contact points`}/><Metric label="Active relationships" value={String(metrics.relationships)} detail={`${metrics.referrals} referrals`}/><Metric label="Open work" value={String(metrics.openTasks)} detail={`${metrics.appointments} appointments`}/></div>
  <div className="crm-home-columns"><section><p className="eyebrow">Today & attention</p><h2>Where the book needs a human next action</h2><p>{missing} visible company record(s) missing a primary contact.</p></section><section><p className="eyebrow">Recent activity</p><h2>Confirmed relationship interactions</h2>{activities.slice(0,4).map(activity=><p key={activity.id}>{formatInTimeZone(activity.occurredAt,timezone)} · {activity.borrowerName} · {activity.subject}</p>)}{!activities.length?<p>No interactions recorded yet.</p>:null}</section></div>
  <div className="crm-diagnostic-strip"><article><strong>Open opportunities</strong><span>{metrics.openOpportunities} authorized deal(s)</span></article><article><strong>Loan exposure</strong><span>{formatMoney(metrics.activeExposure)}</span></article><article><strong>Activity ledger</strong><span>{metrics.activities} interaction(s)</span></article><article><strong>Relationship coverage</strong><span>{missing} visible gap(s)</span></article></div>
  </>}
function Search({view,query}:{view:string;query:string}){return <form className="directory-filters" method="get"><input type="hidden" name="view" value={view}/><label>Search all authorized {label(view)}<input name="q" defaultValue={query} placeholder={`Search ${label(view).toLowerCase()}`}/></label><button type="submit">Search</button>{query?<Link href={`/app/crm?view=${view}`}>Clear</Link>:null}</form>}
function Panel({title,count,total=count,children}:{title:string;count:number;total?:number;children:React.ReactNode}){return <section className="operating-panel crm-directory"><div className="panel-heading"><div><p className="eyebrow">Governed CRM ledger</p><h2>{title}</h2></div><span>{count===total?`${total} visible`:`${count} shown · ${total} authorized`}</span></div>{count?children:<Empty/>}</section>}
function Empty(){return <div className="honest-empty recoverable-empty"><strong>No authorized records match this view.</strong><p>Clear search or use the contextual governed control below to create the first durable record.</p><div className="empty-actions"><Link href="/app/crm?view=companies">Clear search</Link><Link href="/app/intake?surface=crm">Start governed loan deal</Link></div></div>}

function Companies({rows,total}:{rows:BorrowerDirectoryRow[];total:number}){return <Panel title="Companies" count={rows.length} total={total}><div className="directory-table" role="table" aria-label="Company relationship directory"><div className="directory-header" role="row"><span role="columnheader">Company</span><span role="columnheader">Primary contact</span><span role="columnheader">Active deals</span><span role="columnheader">Exposure</span></div>{rows.map(row=><Link className="directory-row" role="row" href={`/app/borrowers/${row.id}`} key={row.id}><span role="cell" data-label="Company"><strong>{row.legalName}</strong><small>{label(row.borrowerKind)} · {row.externalReference??"No reference"}</small></span><span role="cell" data-label="Primary contact">{row.primaryContact??<em>Missing</em>}</span><span role="cell" data-label="Active deals">{row.activeDeals}</span><span role="cell" data-label="Exposure">{formatMoney(row.activeExposure)}</span></Link>)}</div></Panel>}
function People({people,contacts,total,writesEnabled}:{people:CrmPersonRecord[];contacts:CrmContactRecord[];total:number;writesEnabled:boolean}){return <Panel title="People" count={people.length+contacts.length} total={total}><div className="crm-ledger-list">{people.map(person=><article key={person.id}><Link href={`/app/borrowers/${person.borrowerId}`}><strong>{person.preferredName??person.firstName} {person.lastName}</strong><span>{person.roleLabel} · {person.borrowerName}{person.ownershipPercentage!==null?` · ${person.ownershipPercentage}% owner`:""}</span><small>{person.jobTitle??"No title"}{person.email?` · ${person.email}`:""}{person.phone?` · ${person.phone}`:""}{person.isPrimary?" · Primary":""}</small></Link><form action={updateCrmPerson} className="operation-form"><input type="hidden" name="personId" value={person.id}/><input type="hidden" name="expectedVersion" value={person.version}/><input type="hidden" name="idempotencyKey" value={`person-update:${person.id}:${person.version}`}/><label>First name<input name="firstName" defaultValue={person.firstName} required maxLength={100}/></label><label>Middle name<input name="middleName" defaultValue={person.middleName??""} maxLength={100}/></label><label>Last name<input name="lastName" defaultValue={person.lastName} required maxLength={100}/></label><label>Preferred name<input name="preferredName" defaultValue={person.preferredName??""} maxLength={100}/></label><label>Job title<input name="jobTitle" defaultValue={person.jobTitle??""} maxLength={160}/></label><label>Notes<textarea name="notes" defaultValue={person.notes??""} maxLength={4000}/></label><label className="checkbox-field"><input type="checkbox" name="archive" value="true"/>Archive person</label><button disabled={!writesEnabled}>Save person</button></form></article>)}</div>{contacts.length?<div className="activity-ledger"><div><p className="eyebrow">Company contact points</p><h3>Shared addresses, phone numbers, and channels</h3></div><ul>{contacts.map(contact=><li key={contact.id}><span><strong>{contact.borrowerName}</strong><small>{label(contact.kind)} · {contact.value}{contact.isPrimary?" · Primary":""}</small></span><form action={archiveCrmContact}><input type="hidden" name="contactId" value={contact.id}/><input type="hidden" name="expectedVersion" value={contact.version}/><input type="hidden" name="idempotencyKey" value={`contact-archive:${contact.id}:${contact.version}`}/><button disabled={!writesEnabled}>Archive</button></form></li>)}</ul></div>:null}</Panel>}
function Relationships({rows,total,writesEnabled}:{rows:CrmRelationshipRecord[];total:number;writesEnabled:boolean}){return <Panel title="Relationships" count={rows.length} total={total}><div className="crm-ledger-list">{rows.map(row=><article key={row.id}><Link href={`/app/borrowers/${row.sourceBorrowerId}`}><strong>{row.sourceName} → {row.targetName??row.dealName}</strong><span>{label(row.kind)}{row.roleLabel?` · ${row.roleLabel}`:""}</span><small>{row.isActive?"Active":"Inactive"}{row.notes?` · ${row.notes}`:""}</small></Link><form action={row.isActive?closeCrmRelationship:reopenCrmRelationship}><input type="hidden" name="relationshipId" value={row.id}/><input type="hidden" name="idempotencyKey" value={`relationship-${row.isActive?"close":"reopen"}:${row.id}:${randomUUID()}`}/><button disabled={!writesEnabled}>{row.isActive?"End relationship":"Reopen relationship"}</button></form></article>)}</div></Panel>}
function Opportunities({rows,total}:{rows:DealSummary[];total:number}){return <Panel title="Opportunities" count={rows.length} total={total}><div className="crm-ledger-list">{rows.map(row=><Link href={`/app/deals/${row.id}`} key={row.id}><strong>{row.name}</strong><span>{row.borrowerName} · {label(row.stage)}</span><small>{row.dealNumber??"No deal number"} · {formatMoney(row.approvedAmount??row.requestedAmount??0)}</small></Link>)}</div></Panel>}
function Activities({rows,total,timezone}:{rows:CrmActivityRecord[];total:number;timezone:string}){return <Panel title="Activities" count={rows.length} total={total}><div className="crm-ledger-list">{rows.map(row=><Link href={`/app/borrowers/${row.borrowerId}`} key={row.id}><strong>{row.subject}</strong><span>{row.borrowerName} · {label(row.kind)}</span><small>{formatInTimeZone(row.occurredAt,timezone)}{row.notes?` · ${row.notes}`:""}</small></Link>)}</div></Panel>}
function Referrals({rows,total,timezone,writesEnabled}:{rows:CrmReferralRecord[];total:number;timezone:string;writesEnabled:boolean}){return <Panel title="Referrals" count={rows.length} total={total}><div className="crm-ledger-list">{rows.map(row=><article key={row.id}><Link href={`/app/borrowers/${row.borrowerId}`}><strong>{row.borrowerName}</strong><span>From {row.sourceName} · {label(row.status)}</span><small>{formatInTimeZone(row.referredAt,timezone)}{row.estimatedValue!==null?` · ${formatMoney(row.estimatedValue)}`:""}{row.dealName?` · ${row.dealName}`:""}{row.outcome?` · ${row.outcome}`:""}</small></Link><form action={updateCrmReferral} className="operation-form"><input type="hidden" name="referralId" value={row.id}/><input type="hidden" name="expectedVersion" value={row.version}/><input type="hidden" name="idempotencyKey" value={`referral-update:${row.id}:${row.version}`}/><label>Status<select name="status" defaultValue={row.status}><option value="received">Received</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="converted">Converted</option><option value="declined">Declined</option><option value="lost">Lost</option></select></label><label>Outcome<input name="outcome" defaultValue={row.outcome??""} maxLength={500}/></label><label>Notes<textarea name="notes" defaultValue={row.notes??""} maxLength={4000}/></label><button disabled={!writesEnabled}>Save referral</button></form></article>)}</div></Panel>}
function Appointments({rows,operators,total,timezone,writesEnabled}:{rows:CrmAppointmentRecord[];operators:CrmOperatorRecord[];total:number;timezone:string;writesEnabled:boolean}){return <Panel title="Appointments" count={rows.length} total={total}><div className="crm-ledger-list">{rows.map(row=><article key={row.id}><Link href={`/app/borrowers/${row.borrowerId}`}><strong>{row.subject}</strong><span>{row.borrowerName} · {label(row.status)}</span><small>{formatInTimeZone(row.startsAt,timezone)} – {formatInTimeZone(row.endsAt,timezone)}{row.location?` · ${row.location}`:""}</small></Link><form action={updateCrmAppointment} className="operation-form"><input type="hidden" name="appointmentId" value={row.id}/><input type="hidden" name="expectedVersion" value={row.version}/><input type="hidden" name="idempotencyKey" value={`appointment-update:${row.id}:${row.version}`}/><label>Subject<input name="subject" defaultValue={row.subject} required maxLength={200}/></label><label>Starts at ({timezone})<input type="datetime-local" name="startsAt" defaultValue={formatDateTimeLocalInZone(row.startsAt,timezone)} required/></label><label>Ends at ({timezone})<input type="datetime-local" name="endsAt" defaultValue={formatDateTimeLocalInZone(row.endsAt,timezone)} required/></label><label>Status<select name="status" defaultValue={row.status}><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label>Assignee<select name="assignedTo" defaultValue={row.assignedTo??""}><option value="">Unassigned</option>{operators.map(operator=><option value={operator.userId} key={operator.userId}>{operator.displayName}</option>)}</select></label><label>Location<input name="location" defaultValue={row.location??""} maxLength={500}/></label><label>Notes<textarea name="notes" defaultValue={row.notes??""} maxLength={4000}/></label><button disabled={!writesEnabled}>Save appointment</button></form></article>)}</div></Panel>}
function Tasks({rows,operators,total,timezone,writesEnabled}:{rows:DealTaskRecord[];operators:CrmOperatorRecord[];total:number;timezone:string;writesEnabled:boolean}){return <Panel title="Tasks" count={rows.length} total={total}><div className="crm-ledger-list">{rows.map(row=><article key={row.id}><Link href={`/app/deals/${row.dealId}`}><strong>{row.title}</strong><span>{row.dealName} · {label(row.status)}</span><small>{row.dueAt?`Due ${formatInTimeZone(row.dueAt,timezone)}`:"No due date"}{row.assignedTo?" · Assigned":" · Unassigned"}</small></Link>{row.status==="open"?<><form action={updateCrmTask} className="operation-form"><input type="hidden" name="taskId" value={row.id}/><input type="hidden" name="expectedVersion" value={row.version}/><input type="hidden" name="idempotencyKey" value={`task-update:${row.id}:${row.version}`}/><label>Title<input name="title" defaultValue={row.title} required maxLength={200}/></label><label>Description<textarea name="description" defaultValue={row.description??""} maxLength={4000}/></label><label>Due at ({timezone})<input type="datetime-local" name="dueAt" defaultValue={row.dueAt?formatDateTimeLocalInZone(row.dueAt,timezone):""}/></label><label>Assignee<select name="assignedTo" defaultValue={row.assignedTo??""}><option value="">Unassigned</option>{operators.map(operator=><option value={operator.userId} key={operator.userId}>{operator.displayName}</option>)}</select></label><button disabled={!writesEnabled}>Save task</button></form><div className="crm-action-row"><form action={completeCrmTask}><input type="hidden" name="taskId" value={row.id}/><input type="hidden" name="expectedVersion" value={row.version}/><input type="hidden" name="idempotencyKey" value={`task-complete:${row.id}:${row.version}`}/><button disabled={!writesEnabled}>Complete</button></form><form action={updateCrmTask}><input type="hidden" name="taskId" value={row.id}/><input type="hidden" name="expectedVersion" value={row.version}/><input type="hidden" name="idempotencyKey" value={`task-cancel:${row.id}:${row.version}`}/><input type="hidden" name="title" value={row.title}/><input type="hidden" name="description" value={row.description??""}/><input type="hidden" name="dueAt" value={row.dueAt?formatDateTimeLocalInZone(row.dueAt,timezone):""}/><input type="hidden" name="assignedTo" value={row.assignedTo??""}/><input type="hidden" name="cancel" value="true"/><button disabled={!writesEnabled}>Cancel</button></form></div></>:null}</article>)}</div></Panel>}
function Insights({metrics,report}:{metrics:CrmMetrics;report:boolean}){const facts=metrics.companies+metrics.people+metrics.relationships+metrics.activities+metrics.referrals+metrics.appointments+metrics.openTasks+metrics.openOpportunities;return <Panel title={report?"Operating report":"Insights"} count={facts}><div className="crm-metric-grid"><Metric label="Companies" value={String(metrics.companies)} detail={`${metrics.people} people`}/><Metric label="Relationships" value={String(metrics.relationships)} detail={`${metrics.referrals} referrals`}/><Metric label="Opportunities" value={String(metrics.openOpportunities)} detail={formatMoney(metrics.activeExposure)}/><Metric label="Work queue" value={String(metrics.openTasks)} detail={`${metrics.appointments} scheduled`}/></div><p className="empty-copy">Metrics are calculated by the database under the current user&apos;s row-level authorization; they are not inferred from the visible page window.</p></Panel>}
function Metric({label:metricLabel,value,detail}:{label:string;value:string;detail:string}){return <article><span>{metricLabel}</span><strong>{value}</strong><small>{detail}</small></article>}
function Pagination({view,query,page,total}:{view:string;query:string;page:number;total:number}){const pageSize=50,previous=page>1,next=page*pageSize<total,href=(target:number)=>`/app/crm?view=${encodeURIComponent(view)}&page=${target}${query?`&q=${encodeURIComponent(query)}`:""}`;if(!previous&&!next)return null;return <nav className="directory-filters" aria-label={`${label(view)} pagination`}><span>Page {page} · {total} authorized records</span>{previous?<Link href={href(page-1)}>Previous</Link>:null}{next?<Link href={href(page+1)}>Next</Link>:null}</nav>}
function label(value:string){return value.split("_").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ")}
