import Link from "next/link";
import { formatMoney } from "@/components/banker/BankerCommandCenter";
import type { BorrowerDirectoryRow, DealSummary } from "@/lib/los/read-model";
import type { CrmActivityRecord, CrmContactRecord, CrmRelationshipRecord, DealTaskRecord } from "@/lib/los/queries";

const tabs = ["home", "companies", "people", "relationships", "opportunities", "activities", "referrals", "calendar", "tasks", "insights", "reports"] as const;
type Props={rows:BorrowerDirectoryRow[];contacts:CrmContactRecord[];relationships:CrmRelationshipRecord[];deals:DealSummary[];activities:CrmActivityRecord[];tasks:DealTaskRecord[];query:string;view:string;timezone:string};

export function BorrowerDirectory(props:Props){
  const activeView=tabs.includes(props.view as typeof tabs[number])?props.view:"home";
  const filter=(values:string[])=>!props.query||values.join(" ").toLocaleLowerCase().includes(props.query.trim().toLocaleLowerCase());
  const contacts=props.contacts.filter(x=>filter([x.borrowerName,x.kind,x.label??"",x.value]));
  const relationships=props.relationships.filter(x=>filter([x.sourceName,x.targetName??"",x.dealName??"",x.kind,x.roleLabel??""]));
  const deals=props.deals.filter(x=>filter([x.borrowerName,x.name,x.dealNumber??"",x.stage]));
  const activities=props.activities.filter(x=>filter([x.borrowerName,x.kind,x.subject,x.notes??""]));
  const tasks=props.tasks.filter(x=>filter([x.dealName,x.title,x.status,x.description??""]));
  return <section className="crm-command-center">
    <header className="crm-command-header"><div><p className="eyebrow">Relationship intelligence</p><h1>CRM Workspace</h1><p>Companies, people, relationships, activities, opportunities, and work in one governed command center.</p></div><div className="header-actions"><Link className="secondary-button" href="/app/crm?view=activities#crm-operations">Log activity</Link><Link className="primary-button" href="/app/intake?surface=crm">Start governed loan deal</Link></div></header>
    <nav className="crm-tabs" aria-label="CRM sections">{tabs.map(tab=><Link key={tab} className={activeView===tab?"active":""} aria-current={activeView===tab?"page":undefined} href={`/app/crm?view=${tab}`}>{label(tab)}</Link>)}</nav>
    {activeView==="home"?<Home {...props}/>:<><Search view={activeView} query={props.query}/>{activeView==="companies"?<Companies rows={props.rows}/>:activeView==="people"?<People rows={contacts}/>:activeView==="relationships"?<Relationships rows={relationships}/>:activeView==="opportunities"?<Opportunities rows={deals}/>:activeView==="activities"?<Activities rows={activities} timezone={props.timezone}/>:activeView==="referrals"?<Activities rows={activities.filter(x=>x.kind==="referral")} timezone={props.timezone} title="Referrals"/>:activeView==="calendar"?<Activities rows={activities.filter(x=>x.kind==="meeting")} timezone={props.timezone} title="Recorded meetings"/>:activeView==="tasks"?<Tasks rows={tasks} timezone={props.timezone}/>:<Insights {...props} report={activeView==="reports"}/>}</>}
  </section>;
}

function Home({rows,contacts,relationships,deals,activities,tasks,timezone}:Props){
  const exposure=rows.reduce((sum,row)=>sum+row.activeExposure,0), recent=activities.length, scheduled=tasks.filter(x=>x.status==="open"&&x.dueAt).length, missing=rows.filter(x=>!x.primaryContact).length;
  return <><section className="crm-search-deck"><p>Search the relationship book</p><div className="crm-action-row"><form action="/app/crm"><input type="hidden" name="view" value="companies"/><input name="q" aria-label="Search the relationship book" placeholder="Company, person, relationship, activity..."/></form><Link href="/app/crm?view=companies#crm-operations">+ Add Company</Link><Link href="/app/crm?view=people#crm-operations">+ Add Contact</Link><Link href="/app/crm?view=relationships#crm-operations">+ Add Relationship</Link></div></section>
    <div className="crm-metric-grid"><Metric label="Assigned companies" value={String(rows.length)} detail="authorized companies"/><Metric label="People & contact points" value={String(contacts.length)} detail={`${contacts.filter(x=>x.isPrimary).length} primary`}/><Metric label="Active relationships" value={String(relationships.filter(x=>x.isActive).length)} detail="durable links"/><Metric label="Activity ledger" value={String(recent)} detail="authorized interactions"/></div>
    <div className="crm-home-columns"><section><p className="eyebrow">Today & attention</p><h2>Where the book needs a human next action</h2><p>{missing} missing primary contact(s) · {scheduled} scheduled open task(s)</p></section><section><p className="eyebrow">Recent activity</p><h2>Confirmed relationship interactions</h2>{activities.slice(0,4).map(x=><p key={x.id}>{formatDate(x.occurredAt,timezone)} · {x.borrowerName} · {x.subject}</p>)}{!activities.length&&<p>No interactions recorded yet.</p>}</section></div>
    <div className="crm-diagnostic-strip"><article><strong>Open opportunities</strong><span>{deals.length} authorized deal(s)</span></article><article><strong>Loan exposure</strong><span>{formatMoney(exposure)}</span></article><article><strong>Open work</strong><span>{tasks.filter(x=>x.status==="open").length} task(s)</span></article><article><strong>Relationship coverage</strong><span>{missing} company gap(s)</span></article></div></>;
}

function Search({view,query}:{view:string;query:string}){return <form className="directory-filters" method="get"><input type="hidden" name="view" value={view}/><label>Search {label(view)}<input name="q" defaultValue={query} placeholder="Search the authorized ledger"/></label><button type="submit">Search</button>{query&&<Link href={`/app/crm?view=${view}`}>Clear</Link>}</form>}
function Panel({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <section className="operating-panel crm-directory"><div className="panel-heading"><div><p className="eyebrow">Governed CRM ledger</p><h2>{title}</h2></div><span>{count} visible</span></div>{count?children:<Empty/>}</section>}
function Empty(){return <div className="honest-empty recoverable-empty"><strong>No authorized records match this view.</strong><p>Clear search or use the governed controls below to create the first durable record.</p><div className="empty-actions"><Link href="/app/crm?view=companies">Clear search</Link><Link href="/app/intake?surface=crm">Start governed loan deal</Link></div></div>}
function Companies({rows}:{rows:BorrowerDirectoryRow[]}){return <Panel title="Companies" count={rows.length}><div className="directory-table" role="table" aria-label="Company relationship directory"><div className="directory-header" role="row"><span role="columnheader">Company</span><span role="columnheader">Primary contact</span><span role="columnheader">Active deals</span><span role="columnheader">Exposure</span></div>{rows.map(row=><Link className="directory-row" role="row" href={`/app/borrowers/${row.id}`} key={row.id}><span role="cell" data-label="Company"><strong>{row.legalName}</strong><small>{label(row.borrowerKind)} · {row.externalReference??"No reference"}</small></span><span role="cell" data-label="Primary contact">{row.primaryContact??<em>Missing</em>}</span><span role="cell" data-label="Active deals">{row.activeDeals}</span><span role="cell" data-label="Exposure">{formatMoney(row.activeExposure)}</span></Link>)}</div></Panel>}
function People({rows}:{rows:CrmContactRecord[]}){return <Panel title="People & contact points" count={rows.length}><div className="crm-ledger-list">{rows.map(x=><Link href={`/app/borrowers/${x.borrowerId}`} key={x.id}><strong>{x.borrowerName}</strong><span>{label(x.kind)} · {x.value}</span><small>{x.label??"Unlabelled"}{x.isPrimary?" · Primary":""}{x.isVerified?" · Verified":""}</small></Link>)}</div></Panel>}
function Relationships({rows}:{rows:CrmRelationshipRecord[]}){return <Panel title="Relationships" count={rows.length}><div className="crm-ledger-list">{rows.map(x=><Link href={`/app/borrowers/${x.sourceBorrowerId}`} key={x.id}><strong>{x.sourceName} → {x.targetName??x.dealName}</strong><span>{label(x.kind)}{x.roleLabel?` · ${x.roleLabel}`:""}</span><small>{x.isActive?"Active":"Inactive"}{x.notes?` · ${x.notes}`:""}</small></Link>)}</div></Panel>}
function Opportunities({rows}:{rows:DealSummary[]}){return <Panel title="Opportunities" count={rows.length}><div className="crm-ledger-list">{rows.map(x=><Link href={`/app/deals/${x.id}`} key={x.id}><strong>{x.name}</strong><span>{x.borrowerName} · {label(x.stage)}</span><small>{x.dealNumber??"No deal number"} · {formatMoney(x.approvedAmount??x.requestedAmount??0)}</small></Link>)}</div></Panel>}
function Activities({rows,timezone,title="Activities"}:{rows:CrmActivityRecord[];timezone:string;title?:string}){return <Panel title={title} count={rows.length}><div className="crm-ledger-list">{rows.map(x=><Link href={`/app/borrowers/${x.borrowerId}`} key={x.id}><strong>{x.subject}</strong><span>{x.borrowerName} · {label(x.kind)}</span><small>{formatDate(x.occurredAt,timezone)}{x.notes?` · ${x.notes}`:""}</small></Link>)}</div></Panel>}
function Tasks({rows,timezone}:{rows:DealTaskRecord[];timezone:string}){return <Panel title="Tasks" count={rows.length}><div className="crm-ledger-list">{rows.map(x=><Link href={`/app/deals/${x.dealId}`} key={x.id}><strong>{x.title}</strong><span>{x.dealName} · {label(x.status)}</span><small>{x.dueAt?`Due ${formatDate(x.dueAt,timezone)}`:"No due date"}</small></Link>)}</div></Panel>}
function Insights({rows,contacts,relationships,deals,activities,tasks,report}:{rows:BorrowerDirectoryRow[];contacts:CrmContactRecord[];relationships:CrmRelationshipRecord[];deals:DealSummary[];activities:CrmActivityRecord[];tasks:DealTaskRecord[];report:boolean}){const open=tasks.filter(x=>x.status==="open").length,exposure=rows.reduce((n,x)=>n+x.activeExposure,0),facts=rows.length+contacts.length+relationships.length+deals.length+activities.length+tasks.length;return <Panel title={report?"Operating report":"Insights"} count={facts}><div className="crm-metric-grid"><Metric label="Companies" value={String(rows.length)} detail={`${contacts.length} contact points`}/><Metric label="Relationships" value={String(relationships.filter(x=>x.isActive).length)} detail="active links"/><Metric label="Opportunities" value={String(deals.length)} detail={formatMoney(exposure)}/><Metric label="Work queue" value={String(open)} detail={`${activities.length} activities`}/></div></Panel>}
function Metric({label:metricLabel,value,detail}:{label:string;value:string;detail:string}){return <article><span>{metricLabel}</span><strong>{value}</strong><small>{detail}</small></article>}
function label(value:string){return value.split("_").map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(" ")}
function formatDate(value:string,timezone:string){return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone:timezone}).format(new Date(value))}
