import { randomUUID } from "node:crypto";
import Link from "next/link";
import { assignCrmCompany, createCrmAppointment, createCrmCompany, createCrmContact, createCrmPerson, createCrmPersonContact, createCrmReferral, createCrmRelationship, createCrmTask, endCrmCompanyAssignment, logCrmActivity, restoreCrmRecord, updateCrmCompany } from "@/app/app/crm/actions";
import { SubmitButton } from "@/components/app/SubmitButton";
import type { BorrowerDirectoryRow, DealSummary } from "@/lib/los/read-model";
import type { CrmArchivedRecord, CrmOperatorRecord, CrmPersonRecord } from "@/lib/los/queries";
import { LocalDateTimeField } from "./LocalDateTimeField";

type Props={rows:BorrowerDirectoryRow[];deals:DealSummary[];people:CrmPersonRecord[];operators:CrmOperatorRecord[];archivedRecords:CrmArchivedRecord[];assignmentAdmin:boolean;writesEnabled:boolean;error?:string;saved?:string;view:string;pickerQuery:string;timezone:string};

export function CrmOperationsPanel({rows,deals,people,operators,archivedRecords,assignmentAdmin,writesEnabled,error,saved,view,pickerQuery,timezone}:Props){
  return <section id="crm-operations" className="core-operations-panel" aria-label="CRM operating controls">
    <header className="core-operations-header"><div><p className="eyebrow">Governed CRM operations</p><h2>{operationHeading(view)}</h2></div><span className="status-chip">{writesEnabled?"Ready":"Read only"}</span></header>
    {error?<p className="operation-message operation-error">The request was not completed ({error}).</p>:null}
    {saved?<p className="operation-message operation-success">The CRM record was saved.</p>:null}
    <form className="directory-filters" method="get"><input type="hidden" name="view" value={view}/><label>Search operation selectors<input name="pick" defaultValue={pickerQuery} placeholder="Company, opportunity, or person"/></label><button type="submit">Load matches</button>{pickerQuery?<Link href={`/app/crm?view=${view}#crm-operations`}>Clear</Link>:null}</form>
    <p className="empty-copy">Date and time entries use the organization timezone: <strong>{timezone}</strong>.</p>
    <div className="core-operations-grid">{formsForView(view,rows,deals,people,operators,assignmentAdmin,writesEnabled,timezone)}{archivedRecords.map(record=><RestoreForm key={`${record.entity}:${record.id}`} record={record} enabled={writesEnabled}/>)}</div>
  </section>;
}

function formsForView(view:string,rows:BorrowerDirectoryRow[],deals:DealSummary[],people:CrmPersonRecord[],operators:CrmOperatorRecord[],assignmentAdmin:boolean,enabled:boolean,timezone:string){
  if(view==="people")return <><OperationForm title="Add person" action={createCrmPerson} enabled={enabled&&rows.length>0}>
    <input type="hidden" name="idempotencyKey" value={`person:${randomUUID()}`}/><BorrowerSelect rows={rows}/>
    <label>First name<input name="firstName" required minLength={1} maxLength={100}/></label><label>Middle name<input name="middleName" maxLength={100}/></label><label>Last name<input name="lastName" required minLength={1} maxLength={100}/></label><label>Preferred name<input name="preferredName" maxLength={100}/></label><label>Job title<input name="jobTitle" maxLength={160}/></label><label>Company role<input name="roleLabel" required minLength={2} maxLength={120} placeholder="Owner, president, controller…"/></label><label>Ownership percentage<input name="ownershipPercentage" type="number" min="0" max="100" step="0.01"/></label><label>Email<input name="email" type="email" maxLength={500}/></label><label>Phone<input name="phone" type="tel" maxLength={30}/></label><label className="checkbox-field"><input name="isPrimary" type="checkbox"/>Primary company contact</label><label>Notes<textarea name="notes" maxLength={4000}/></label>
  </OperationForm><OperationForm title="Add person contact" action={createCrmPersonContact} enabled={enabled&&people.length>0}><input type="hidden" name="idempotencyKey" value={`person-contact:${randomUUID()}`}/><PersonSelect people={people}/><ContactFields/></OperationForm><OperationForm title="Add company contact point" action={createCrmContact} enabled={enabled&&rows.length>0}><input type="hidden" name="idempotencyKey" value={`contact:${randomUUID()}`}/><BorrowerSelect rows={rows}/><ContactFields/></OperationForm></>;
  if(view==="relationships")return <OperationForm title="Add relationship" action={createCrmRelationship} enabled={enabled&&rows.length>1}><input type="hidden" name="idempotencyKey" value={`relationship:${randomUUID()}`}/><BorrowerSelect rows={rows} name="sourceBorrowerId" label="Source company"/><BorrowerSelect rows={rows} name="targetBorrowerId" label="Related company"/><label>Relationship type<select name="relationshipKind" defaultValue="affiliate"><option value="guarantor">Guarantor</option><option value="owner">Owner</option><option value="officer">Officer</option><option value="advisor">Advisor</option><option value="vendor">Vendor</option><option value="affiliate">Affiliate</option><option value="other">Other</option></select></label><label>Role label<input name="roleLabel" maxLength={120}/></label><label>Notes<textarea name="notes" maxLength={4000}/></label></OperationForm>;
  if(view==="activities")return <OperationForm title="Log activity" action={logCrmActivity} enabled={enabled&&rows.length>0}><input type="hidden" name="idempotencyKey" value={`activity:${randomUUID()}`}/><BorrowerSelect rows={rows}/><DealSelect deals={deals} optional/><p className="empty-copy">If an opportunity is selected, it must belong to the selected company.</p><label>Activity type<select name="activityKind" defaultValue="call"><option value="call">Call</option><option value="email">Email</option><option value="meeting">Meeting</option><option value="note">Note</option><option value="referral">Referral note</option><option value="other">Other</option></select></label><label>Subject<input name="subject" required minLength={2} maxLength={200}/></label><LocalDateTimeField name="occurredAt" label="Occurred at" timezone={timezone} required/><label>Notes<textarea name="notes" maxLength={4000}/></label></OperationForm>;
  if(view==="tasks")return <OperationForm title="Create assigned task" action={createCrmTask} enabled={enabled&&deals.length>0}><input type="hidden" name="idempotencyKey" value={`task:${randomUUID()}`}/><DealSelect deals={deals}/><label>Title<input name="title" required minLength={2} maxLength={200}/></label><label>Description<textarea name="description" maxLength={4000}/></label><LocalDateTimeField name="dueAt" label="Due at" timezone={timezone}/><p className="empty-copy">The task is assigned to you. Edit, reassign, complete, or cancel it from the task ledger.</p></OperationForm>;
  if(view==="referrals")return <OperationForm title="Record referral" action={createCrmReferral} enabled={enabled&&rows.length>0&&(rows.length>1||people.length>0)}><input type="hidden" name="idempotencyKey" value={`referral:${randomUUID()}`}/><BorrowerSelect rows={rows} label="Referred company"/><BorrowerSelect rows={rows} name="sourceBorrowerId" label="Referral source company (optional)" optional/><PersonSelect people={people} name="sourcePersonId" label="Referral source person (optional)" optional/><p className="empty-copy">Choose either a source company or source person.</p><DealSelect deals={deals} optional/><LocalDateTimeField name="referredAt" label="Referred at" timezone={timezone} required/><label>Estimated value<input name="estimatedValue" type="number" min="0" step="0.01"/></label><label>Notes<textarea name="notes" maxLength={4000}/></label></OperationForm>;
  if(view==="calendar")return <OperationForm title="Schedule appointment" action={createCrmAppointment} enabled={enabled&&rows.length>0}><input type="hidden" name="idempotencyKey" value={`appointment:${randomUUID()}`}/><BorrowerSelect rows={rows}/><DealSelect deals={deals} optional/><p className="empty-copy">If an opportunity is selected, it must belong to the selected company.</p><label>Subject<input name="subject" required minLength={2} maxLength={200}/></label><LocalDateTimeField name="startsAt" label="Starts at" timezone={timezone} required/><LocalDateTimeField name="endsAt" label="Ends at" timezone={timezone} required/><label>Location or meeting link<input name="location" maxLength={500}/></label><label>Notes<textarea name="notes" maxLength={4000}/></label></OperationForm>;
  if(view==="companies")return <><CompanyCreate enabled={enabled}/><OperationForm title="Update company" action={updateCrmCompany} enabled={enabled&&rows.length>0}><input type="hidden" name="idempotencyKey" value={`company-update:${randomUUID()}`}/><CompanyVersionSelect rows={rows}/><label>Legal name<input name="legalName" required minLength={2} maxLength={200}/></label><label>External reference<input name="externalReference" maxLength={120}/></label><p className="empty-copy">The current version is protected by optimistic concurrency. To archive, select the company and check the control below.</p><label className="checkbox-field"><input name="archive" type="checkbox" value="true"/>Archive this company</label></OperationForm>{assignmentAdmin?<><AssignmentForm title="Assign lender" action={assignCrmCompany} rows={rows} operators={operators} enabled={enabled}/><AssignmentForm title="End lender assignment" action={endCrmCompanyAssignment} rows={rows} operators={operators} enabled={enabled}/></>:null}</>;
  return <CompanyCreate enabled={enabled}/>;
}

function CompanyCreate({enabled}:{enabled:boolean}){return <OperationForm title="Add company" action={createCrmCompany} enabled={enabled}><input type="hidden" name="idempotencyKey" value={`company:${randomUUID()}`}/><label>Legal name<input name="legalName" minLength={2} maxLength={200} required/></label><label>Borrower type<select name="borrowerKind" defaultValue="business"><option value="business">Business</option><option value="individual">Individual</option><option value="trust">Trust</option><option value="government">Government</option><option value="nonprofit">Nonprofit</option><option value="other">Other</option></select></label><label>External reference<input name="externalReference" maxLength={120}/></label></OperationForm>}
function BorrowerSelect({rows,name="borrowerId",label="Company",optional=false}:{rows:BorrowerDirectoryRow[];name?:string;label?:string;optional?:boolean}){return <label>{label}<select name={name} required={!optional} defaultValue=""><option value="" disabled={!optional}>{optional?"No company selected":"Select a company"}</option>{rows.map(row=><option value={row.id} key={row.id}>{row.legalName}</option>)}</select></label>}
function CompanyVersionSelect({rows}:{rows:BorrowerDirectoryRow[]}){return <label>Company<select name="companySelection" required defaultValue=""><option value="" disabled>Select a company</option>{rows.map(row=><option value={`${row.id}:${row.version}`} key={row.id}>{row.legalName} · v{row.version}</option>)}</select></label>}
function DealSelect({deals,optional=false}:{deals:DealSummary[];optional?:boolean}){return <label>{optional?"Related opportunity (optional)":"Opportunity"}<select name="dealId" required={!optional} defaultValue=""><option value="" disabled={!optional}>{optional?"No related opportunity":"Select an opportunity"}</option>{deals.map(deal=><option value={deal.id} key={deal.id}>{deal.borrowerName} · {deal.name}</option>)}</select></label>}
function PersonSelect({people,name="personId",label="Person",optional=false}:{people:CrmPersonRecord[];name?:string;label?:string;optional?:boolean}){return <label>{label}<select name={name} required={!optional} defaultValue=""><option value="" disabled={!optional}>{optional?"No person selected":"Select a person"}</option>{people.map(person=><option value={person.id} key={person.id}>{person.preferredName??person.firstName} {person.lastName} · {person.borrowerName}</option>)}</select></label>}
function ContactFields(){return <><label>Contact type<select name="contactKind" defaultValue="email"><option value="email">Email</option><option value="phone">Phone</option><option value="address">Address</option><option value="website">Website</option><option value="other">Other</option></select></label><label>Value<input name="value" required maxLength={500}/></label><label>Label<input name="label" maxLength={80}/></label><label className="checkbox-field"><input name="isPrimary" type="checkbox"/>Primary for this type</label></>}
function AssignmentForm({title,action,rows,operators,enabled}:{title:string;action:(form:FormData)=>Promise<void>;rows:BorrowerDirectoryRow[];operators:CrmOperatorRecord[];enabled:boolean}){return <OperationForm title={title} action={action} enabled={enabled&&rows.length>0&&operators.some(operator=>operator.role==="lender")}><input type="hidden" name="idempotencyKey" value={`assignment:${randomUUID()}`}/><BorrowerSelect rows={rows}/><label>Lender<select name="userId" required defaultValue=""><option value="" disabled>Select a lender</option>{operators.filter(operator=>operator.role==="lender").map(operator=><option value={operator.userId} key={operator.userId}>{operator.displayName}</option>)}</select></label></OperationForm>}
function OperationForm({title,action,enabled,children}:{title:string;action:(form:FormData)=>Promise<void>;enabled:boolean;children:React.ReactNode}){return <form action={action} className="operation-form"><h3>{title}</h3>{children}{enabled?<SubmitButton idle={title} pending={`${title}…`}/>:<button className="button-primary" disabled>Writes disabled</button>}</form>}
function RestoreForm({record,enabled}:{record:CrmArchivedRecord;enabled:boolean}){return <OperationForm title={`Restore ${record.entity}`} action={restoreCrmRecord} enabled={enabled}><input type="hidden" name="entityId" value={record.id}/><input type="hidden" name="entity" value={record.entity}/><input type="hidden" name="expectedVersion" value={record.version}/><input type="hidden" name="idempotencyKey" value={`restore:${record.entity}:${record.id}:${record.version}`}/><p>{record.label}</p><p className="empty-copy">Archived record · version {record.version}</p></OperationForm>}
function operationHeading(view:string){const labels:Record<string,string>={companies:"Company lifecycle",people:"People and contact lifecycle",relationships:"Relationship lifecycle",activities:"Activity ledger",referrals:"Referral pipeline",calendar:"Appointment calendar",tasks:"Assigned work queue"};return labels[view]??"Relationship book controls"}
